version: '3.8'
services:
  mongo-db:
    image: mongo:jammy
    restart: always
    container_name: mongo-db
    volumes:
      - ./volumes/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=svkm
      - MONGO_INITDB_ROOT_PASSWORD=svkm-mongo-node-1
      - MONGO_INITDB_DATABASE=svkm
    ports:
      - "27017-27019:27017-27019"

  svkm:
    image: ghcr.io/alexzedim/svkm:latest
    container_name: svkm
    restart: always
    command: [ 'node', 'dist/main.js' ]
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_CONNECTION=mongodb://svkm:svkm-mongo-node-1@mongo-db:27017/admin?authSource=admin&readPreference=primary

# networks:
  # Сеть нам не нужна, но можно, и указывать в config адреса контейнеров вместо localhost
  # svkm-network:
    # driver: bridge

volumes:
  mongo:
