name: Create SVKM Image

on:
  push:
    branches: [ master ]
    paths:
      - 'apps/svkm/**'
      - 'libs/**'

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/alexzedim/svkm
          tags: |
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.version }}
          labels: |
            org.opencontainers.image.title = "SVKM"
            org.opencontainers.image.vendor = "alexzedim"
            org.opencontainers.image.source = "https://github.com/AlexZeDim/svkm"
            org.opencontainers.image.licenses = "MPL 2.0"
            org.opencontainers.image.description = "SVKM"

      - name: Login to Github Packages
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build & Push (GHCR)
        uses: docker/build-push-action@v4.1.1
        with:
          file: ./Dockerfile
          push: true
          tags: ghcr.io/alexzedim/svkm:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CR_PAT=${{ secrets.CR_PAT }}

      - name: Image digest
        run: echo ${{ steps.build-push-action.outputs.digest }}
